import type { Metadata } from "next";
import "./globals.css";
import { Macondo } from "next/font/google";


const macondo = Macondo({
  subsets: ["latin"],
  weight: "400",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${macondo.className} antialiased bg-[#ffd6d6]`}>
        {children}
      </body>
    </html>
  );
}
